import type { Exercise } from "./types";

// The exercise library. Tiers (S/A/B) follow a Jeff Nippard-style ranking of
// stimulus quality / efficiency for hypertrophy. This list is the master
// catalogue the app suggests from and lets you swap between.
export const EXERCISES: Exercise[] = [
  // ---- CHEST ----
  {
    id: "incline-db-press",
    name: "Incline Dumbbell Press",
    primaryMuscle: "chest",
    secondaryMuscles: ["front-delts", "triceps"],
    tier: "S",
    equipment: "dumbbell",
    repRange: { min: 8, max: 12 },
    targetRIR: 1,
    note: "Great upper-chest stretch and stability. A staple pressing movement.",
  },
  {
    id: "machine-chest-press",
    name: "Machine Chest Press",
    primaryMuscle: "chest",
    secondaryMuscles: ["front-delts", "triceps"],
    tier: "S",
    equipment: "machine",
    repRange: { min: 8, max: 12 },
    targetRIR: 1,
    note: "Stable, easy to push close to failure safely.",
  },
  {
    id: "barbell-bench-press",
    name: "Barbell Bench Press",
    primaryMuscle: "chest",
    secondaryMuscles: ["front-delts", "triceps"],
    tier: "A",
    equipment: "barbell",
    repRange: { min: 6, max: 10 },
    targetRIR: 2,
    note: "Heavy compound. Strong but a bit harder on the shoulders.",
  },
  {
    id: "pec-deck",
    name: "Pec Deck / Cable Fly",
    primaryMuscle: "chest",
    tier: "A",
    equipment: "machine",
    repRange: { min: 12, max: 20 },
    targetRIR: 1,
    note: "Isolation with a great stretch on the chest.",
  },

  // ---- SHOULDERS ----
  {
    id: "db-shoulder-press",
    name: "Dumbbell Shoulder Press",
    primaryMuscle: "front-delts",
    secondaryMuscles: ["side-delts", "triceps"],
    tier: "S",
    equipment: "dumbbell",
    repRange: { min: 8, max: 12 },
    targetRIR: 1,
    note: "Main front-delt builder.",
  },
  {
    id: "cable-lateral-raise",
    name: "Cable Lateral Raise",
    primaryMuscle: "side-delts",
    tier: "S",
    equipment: "cable",
    repRange: { min: 12, max: 20 },
    targetRIR: 0,
    note: "Constant tension on side delts — width maker.",
  },
  {
    id: "db-lateral-raise",
    name: "Dumbbell Lateral Raise",
    primaryMuscle: "side-delts",
    tier: "A",
    equipment: "dumbbell",
    repRange: { min: 12, max: 20 },
    targetRIR: 0,
    note: "Classic side-delt isolation.",
  },
  {
    id: "machine-lateral-raise",
    name: "Machine Lateral Raise",
    primaryMuscle: "side-delts",
    tier: "S",
    equipment: "machine",
    repRange: { min: 12, max: 20 },
    targetRIR: 0,
    note: "Thor plan: capped, wide delts — trained 3×/week. Stable so you can chase the burn.",
    tags: ["thor"],
  },
  {
    id: "reverse-pec-deck",
    name: "Reverse Pec Deck",
    primaryMuscle: "rear-delts",
    tier: "S",
    equipment: "machine",
    repRange: { min: 12, max: 20 },
    targetRIR: 0,
    note: "Best rear-delt isolation for most people.",
  },
  {
    id: "cable-rear-delt-fly",
    name: "Cable Rear Delt Fly",
    primaryMuscle: "rear-delts",
    tier: "A",
    equipment: "cable",
    repRange: { min: 12, max: 20 },
    targetRIR: 0,
  },

  // ---- TRICEPS ----
  {
    id: "cable-pushdown",
    name: "Cable Triceps Pushdown",
    primaryMuscle: "triceps",
    tier: "S",
    equipment: "cable",
    repRange: { min: 10, max: 15 },
    targetRIR: 1,
    note: "Reliable triceps pump with constant tension.",
  },
  {
    id: "overhead-cable-ext",
    name: "Overhead Cable Extension",
    primaryMuscle: "triceps",
    tier: "S",
    equipment: "cable",
    repRange: { min: 10, max: 15 },
    targetRIR: 1,
    note: "Stretches the long head of the triceps.",
  },
  {
    id: "skull-crushers",
    name: "Skull Crushers",
    primaryMuscle: "triceps",
    tier: "A",
    equipment: "barbell",
    repRange: { min: 8, max: 12 },
    targetRIR: 2,
    note: "Lying triceps extension — loads the long head hard.",
  },
  {
    id: "dips",
    name: "Dips",
    primaryMuscle: "triceps",
    secondaryMuscles: ["chest", "front-delts"],
    tier: "A",
    equipment: "bodyweight",
    repRange: { min: 8, max: 15 },
    targetRIR: 2,
  },
  {
    id: "close-grip-bench-press",
    name: "Close-Grip Bench Press",
    primaryMuscle: "triceps",
    secondaryMuscles: ["chest", "front-delts"],
    tier: "A",
    equipment: "barbell",
    repRange: { min: 6, max: 10 },
    targetRIR: 2,
    note: "Thor plan: heavy compound for thick arms. Pair with a pushdown for volume.",
    tags: ["thor"],
  },

  // ---- BACK ----
  {
    id: "lat-pulldown",
    name: "Lat Pulldown",
    primaryMuscle: "lats",
    secondaryMuscles: ["biceps", "back"],
    tier: "S",
    equipment: "cable",
    repRange: { min: 8, max: 12 },
    targetRIR: 1,
    note: "Builds lat width with a controllable load.",
  },
  {
    id: "chest-supported-row",
    name: "Chest-Supported Row",
    primaryMuscle: "back",
    secondaryMuscles: ["lats", "biceps", "rear-delts"],
    tier: "S",
    equipment: "machine",
    repRange: { min: 8, max: 12 },
    targetRIR: 1,
    note: "Thickness builder with no lower-back strain.",
  },
  {
    id: "pull-ups",
    name: "Pull-Ups",
    primaryMuscle: "lats",
    secondaryMuscles: ["biceps", "back"],
    tier: "A",
    equipment: "bodyweight",
    repRange: { min: 6, max: 12 },
    targetRIR: 2,
  },
  {
    id: "straight-arm-pulldown",
    name: "Straight-Arm Pulldown",
    primaryMuscle: "lats",
    tier: "A",
    equipment: "cable",
    repRange: { min: 12, max: 20 },
    targetRIR: 1,
    note: "Thor plan: lat-width isolation, no biceps fatigue. A core 3×/week movement.",
    tags: ["thor"],
  },
  {
    id: "db-pullover",
    name: "Dumbbell Pullover",
    primaryMuscle: "lats",
    secondaryMuscles: ["chest"],
    tier: "A",
    equipment: "dumbbell",
    repRange: { min: 10, max: 15 },
    targetRIR: 1,
    note: "Thor plan: big lat stretch for that V-taper sweep.",
    tags: ["thor"],
  },
  {
    id: "barbell-row",
    name: "Barbell Row",
    primaryMuscle: "back",
    secondaryMuscles: ["lats", "biceps", "rear-delts"],
    tier: "A",
    equipment: "barbell",
    repRange: { min: 6, max: 10 },
    targetRIR: 2,
  },

  // ---- BICEPS ----
  {
    id: "incline-db-curl",
    name: "Incline Dumbbell Curl",
    primaryMuscle: "biceps",
    tier: "S",
    equipment: "dumbbell",
    repRange: { min: 8, max: 12 },
    targetRIR: 1,
    note: "Stretched-position curl — excellent biceps growth.",
  },
  {
    id: "cable-curl",
    name: "Cable Curl",
    primaryMuscle: "biceps",
    tier: "S",
    equipment: "cable",
    repRange: { min: 10, max: 15 },
    targetRIR: 1,
  },
  {
    id: "ez-bar-curl",
    name: "EZ-Bar Curl",
    primaryMuscle: "biceps",
    tier: "A",
    equipment: "barbell",
    repRange: { min: 8, max: 12 },
    targetRIR: 1,
  },
  {
    id: "hammer-curl",
    name: "Hammer Curl",
    primaryMuscle: "biceps",
    tier: "A",
    equipment: "dumbbell",
    repRange: { min: 8, max: 12 },
    targetRIR: 1,
    note: "Thor plan: builds arm thickness by hitting the brachialis and forearms.",
    tags: ["thor"],
  },
  {
    id: "preacher-curl",
    name: "Preacher Curl",
    primaryMuscle: "biceps",
    tier: "A",
    equipment: "machine",
    repRange: { min: 10, max: 15 },
    targetRIR: 1,
    note: "Thor plan: stretched-position curl with no swinging — pure biceps.",
    tags: ["thor"],
  },

  // ---- QUADS ----
  {
    id: "hack-squat",
    name: "Hack Squat",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes"],
    tier: "S",
    equipment: "machine",
    repRange: { min: 8, max: 12 },
    targetRIR: 1,
    note: "Loads the quads hard with a stable path.",
  },
  {
    id: "leg-press",
    name: "Leg Press",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes"],
    tier: "S",
    equipment: "machine",
    repRange: { min: 10, max: 15 },
    targetRIR: 1,
  },
  {
    id: "barbell-squat",
    name: "Barbell Back Squat",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes", "hamstrings"],
    tier: "A",
    equipment: "barbell",
    repRange: { min: 6, max: 10 },
    targetRIR: 2,
  },
  {
    id: "leg-extension",
    name: "Leg Extension",
    primaryMuscle: "quads",
    tier: "A",
    equipment: "machine",
    repRange: { min: 12, max: 20 },
    targetRIR: 0,
    note: "Pure quad isolation, great for adding volume.",
  },

  // ---- HAMSTRINGS ----
  {
    id: "seated-leg-curl",
    name: "Seated Leg Curl",
    primaryMuscle: "hamstrings",
    tier: "S",
    equipment: "machine",
    repRange: { min: 10, max: 15 },
    targetRIR: 1,
    note: "Trains hamstrings in a stretched position — top tier.",
  },
  {
    id: "romanian-deadlift",
    name: "Romanian Deadlift",
    primaryMuscle: "hamstrings",
    secondaryMuscles: ["glutes", "back"],
    tier: "S",
    equipment: "barbell",
    repRange: { min: 8, max: 12 },
    targetRIR: 2,
    note: "Big hamstring & glute stretch under load.",
  },
  {
    id: "lying-leg-curl",
    name: "Lying Leg Curl",
    primaryMuscle: "hamstrings",
    tier: "A",
    equipment: "machine",
    repRange: { min: 10, max: 15 },
    targetRIR: 1,
  },

  // ---- GLUTES ----
  {
    id: "hip-thrust",
    name: "Barbell Hip Thrust",
    primaryMuscle: "glutes",
    secondaryMuscles: ["hamstrings"],
    tier: "S",
    equipment: "barbell",
    repRange: { min: 8, max: 12 },
    targetRIR: 1,
    note: "Peak-contraction glute builder.",
  },
  {
    id: "cable-kickback",
    name: "Cable Glute Kickback",
    primaryMuscle: "glutes",
    tier: "A",
    equipment: "cable",
    repRange: { min: 12, max: 20 },
    targetRIR: 0,
  },

  // ---- CALVES ----
  {
    id: "standing-calf-raise",
    name: "Standing Calf Raise",
    primaryMuscle: "calves",
    tier: "S",
    equipment: "machine",
    repRange: { min: 10, max: 15 },
    targetRIR: 1,
    note: "Pause at the bottom stretch for best results.",
  },
  {
    id: "seated-calf-raise",
    name: "Seated Calf Raise",
    primaryMuscle: "calves",
    tier: "A",
    equipment: "machine",
    repRange: { min: 12, max: 20 },
    targetRIR: 1,
  },
];

// Quick lookup by id.
export const EXERCISE_MAP: Record<string, Exercise> = Object.fromEntries(
  EXERCISES.map((e) => [e.id, e]),
);

export function getExercise(id: string): Exercise | undefined {
  return EXERCISE_MAP[id];
}

const TIER_RANK = { S: 0, A: 1, B: 2 } as const;

// All exercises that primarily train a muscle, ranked best-first (S→A→B, then
// alphabetical). Used to suggest swaps.
export function alternativesForMuscle(muscle: Exercise["primaryMuscle"]): Exercise[] {
  return EXERCISES.filter((e) => e.primaryMuscle === muscle).sort(
    (a, b) => TIER_RANK[a.tier] - TIER_RANK[b.tier] || a.name.localeCompare(b.name),
  );
}
