import type { Exercise } from "./types";

// The exercise library. Tiers (S/A/B) follow a Jeff Nippard-style ranking of
// stimulus quality / efficiency for hypertrophy. This list is the master
// catalogue the app suggests from and lets you swap between. Every exercise
// carries a short plain-English form cue in `note`.
export const EXERCISES: Exercise[] = [
  // ---- CHEST ----
  {
    id: "incline-db-press",
    name: "Incline Dumbbell Press",
    primaryMuscle: "chest",
    secondaryMuscles: ["front-delts", "triceps"],
    tier: "S",
    equipment: "dumbbell",
    repRange: { min: 8, max: 12 },
    targetRIR: 1,
    note: "Bench at ~30°. Lower under control for a deep stretch at the bottom, then press without clashing the dumbbells at the top.",
  },
  {
    id: "machine-chest-press",
    name: "Machine Chest Press",
    primaryMuscle: "chest",
    secondaryMuscles: ["front-delts", "triceps"],
    tier: "S",
    equipment: "machine",
    repRange: { min: 8, max: 12 },
    targetRIR: 1,
    note: "Set the seat so the handles sit at mid-chest; stable, so it's easy to push close to failure safely.",
  },
  {
    id: "barbell-bench-press",
    name: "Barbell Bench Press",
    primaryMuscle: "chest",
    secondaryMuscles: ["front-delts", "triceps"],
    tier: "A",
    equipment: "barbell",
    repRange: { min: 6, max: 10 },
    targetRIR: 2,
    note: "Tuck the elbows ~45°, touch the lower chest, and keep the shoulder blades pinned back and down.",
  },
  {
    id: "pec-deck",
    name: "Pec Deck / Cable Fly",
    primaryMuscle: "chest",
    tier: "A",
    equipment: "machine",
    repRange: { min: 12, max: 20 },
    targetRIR: 1,
    note: "Keep a soft elbow bend fixed throughout and squeeze the hands together; let the chest stretch fully on the way out.",
  },

  // ---- SHOULDERS ----
  {
    id: "db-shoulder-press",
    name: "Dumbbell Shoulder Press",
    primaryMuscle: "front-delts",
    secondaryMuscles: ["side-delts", "triceps"],
    tier: "S",
    equipment: "dumbbell",
    repRange: { min: 8, max: 12 },
    targetRIR: 1,
    note: "Press just short of locking out and lower until the elbows drop below shoulder level; avoid arching the lower back.",
  },
  {
    id: "cable-lateral-raise",
    name: "Cable Lateral Raise",
    primaryMuscle: "side-delts",
    tier: "S",
    equipment: "cable",
    repRange: { min: 12, max: 20 },
    targetRIR: 0,
    note: "Lead with the elbow, raise to shoulder height, and resist the negative — constant tension makes this a width builder.",
  },
  {
    id: "db-lateral-raise",
    name: "Dumbbell Lateral Raise",
    primaryMuscle: "side-delts",
    tier: "A",
    equipment: "dumbbell",
    repRange: { min: 12, max: 20 },
    targetRIR: 0,
    note: "Slight forward lean, raise out to the sides to shoulder height, and don't swing or shrug the traps up.",
  },
  {
    id: "machine-lateral-raise",
    name: "Machine Lateral Raise",
    primaryMuscle: "side-delts",
    tier: "S",
    equipment: "machine",
    repRange: { min: 12, max: 20 },
    targetRIR: 0,
    note: "Thor plan: capped, wide delts, trained 3×/week. Push the pads with the elbows to shoulder height and chase a controlled burn.",
    tags: ["thor"],
  },
  {
    id: "reverse-pec-deck",
    name: "Reverse Pec Deck",
    primaryMuscle: "rear-delts",
    tier: "S",
    equipment: "machine",
    repRange: { min: 12, max: 20 },
    targetRIR: 0,
    note: "Lead with the elbows out and back, stop level with the torso, and keep the chest pinned to the pad.",
  },
  {
    id: "cable-rear-delt-fly",
    name: "Cable Rear Delt Fly",
    primaryMuscle: "rear-delts",
    tier: "A",
    equipment: "cable",
    repRange: { min: 12, max: 20 },
    targetRIR: 0,
    note: "Cross the cables, lead with the elbows out to the sides at shoulder height — think pulling apart, not lifting.",
  },

  // ---- TRICEPS ----
  {
    id: "cable-pushdown",
    name: "Cable Triceps Pushdown",
    primaryMuscle: "triceps",
    tier: "S",
    equipment: "cable",
    repRange: { min: 10, max: 15 },
    targetRIR: 1,
    note: "Pin the elbows to your sides and extend fully; only the forearms move.",
  },
  {
    id: "overhead-cable-ext",
    name: "Overhead Cable Extension",
    primaryMuscle: "triceps",
    tier: "S",
    equipment: "cable",
    repRange: { min: 10, max: 15 },
    targetRIR: 1,
    note: "Lean away from the stack so the upper arms stay overhead, and let the long head stretch deeply before extending.",
  },
  {
    id: "skull-crushers",
    name: "Skull Crushers",
    primaryMuscle: "triceps",
    tier: "A",
    equipment: "barbell",
    repRange: { min: 8, max: 12 },
    targetRIR: 2,
    note: "Keep the upper arms angled slightly back and lower toward the forehead/behind the head to load the long head.",
  },
  {
    id: "dips",
    name: "Dips",
    primaryMuscle: "triceps",
    secondaryMuscles: ["chest", "front-delts"],
    tier: "A",
    equipment: "bodyweight",
    repRange: { min: 8, max: 15 },
    targetRIR: 2,
    note: "Stay upright with elbows tucked for triceps (lean forward for chest); lower until the upper arms reach parallel.",
  },
  {
    id: "close-grip-bench-press",
    name: "Close-Grip Bench Press",
    primaryMuscle: "triceps",
    secondaryMuscles: ["chest", "front-delts"],
    tier: "A",
    equipment: "barbell",
    repRange: { min: 6, max: 10 },
    targetRIR: 2,
    note: "Thor plan: heavy compound for thick arms. Grip about shoulder-width, tuck the elbows, and touch the lower chest. Pair with a pushdown for volume.",
    tags: ["thor"],
  },

  // ---- BACK ----
  {
    id: "lat-pulldown",
    name: "Lat Pulldown",
    primaryMuscle: "lats",
    secondaryMuscles: ["biceps", "back"],
    tier: "S",
    equipment: "cable",
    repRange: { min: 8, max: 12 },
    targetRIR: 1,
    note: "Drive the elbows down toward the hips and bring the bar to the upper chest; let the lats stretch fully at the top.",
  },
  {
    id: "chest-supported-row",
    name: "Chest-Supported Row",
    primaryMuscle: "back",
    secondaryMuscles: ["lats", "biceps", "rear-delts"],
    tier: "S",
    equipment: "machine",
    repRange: { min: 8, max: 12 },
    targetRIR: 1,
    note: "Keep the chest on the pad, row to the lower ribs by driving the elbows back, and squeeze the shoulder blades together.",
  },
  {
    id: "pull-ups",
    name: "Pull-Ups",
    primaryMuscle: "lats",
    secondaryMuscles: ["biceps", "back"],
    tier: "A",
    equipment: "bodyweight",
    repRange: { min: 6, max: 12 },
    targetRIR: 2,
    note: "Start from a full dead hang, drive the elbows down and back, and pull the chest toward the bar without kipping.",
  },
  {
    id: "straight-arm-pulldown",
    name: "Straight-Arm Pulldown",
    primaryMuscle: "lats",
    tier: "A",
    equipment: "cable",
    repRange: { min: 12, max: 20 },
    targetRIR: 1,
    note: "Thor plan: lat-width isolation with no biceps fatigue. Keep the arms nearly straight and sweep the bar to the thighs using the lats.",
    tags: ["thor"],
  },
  {
    id: "db-pullover",
    name: "Dumbbell Pullover",
    primaryMuscle: "lats",
    secondaryMuscles: ["chest"],
    tier: "A",
    equipment: "dumbbell",
    repRange: { min: 10, max: 15 },
    targetRIR: 1,
    note: "Thor plan: big lat stretch for the V-taper. Lower the dumbbell back over the head with a slight elbow bend, feeling the stretch, then pull it over the chest.",
    tags: ["thor"],
  },
  {
    id: "barbell-row",
    name: "Barbell Row",
    primaryMuscle: "back",
    secondaryMuscles: ["lats", "biceps", "rear-delts"],
    tier: "A",
    equipment: "barbell",
    repRange: { min: 6, max: 10 },
    targetRIR: 2,
    note: "Hinge to about 45°, keep the lower back flat and braced, and row to the lower ribs with the elbows tucked.",
  },

  // ---- BICEPS ----
  {
    id: "incline-db-curl",
    name: "Incline Dumbbell Curl",
    primaryMuscle: "biceps",
    tier: "S",
    equipment: "dumbbell",
    repRange: { min: 8, max: 12 },
    targetRIR: 1,
    note: "Let the arms hang behind the torso on an incline bench for a deep stretch, then curl without the elbows drifting forward.",
  },
  {
    id: "cable-curl",
    name: "Cable Curl",
    primaryMuscle: "biceps",
    tier: "S",
    equipment: "cable",
    repRange: { min: 10, max: 15 },
    targetRIR: 1,
    note: "Pin the elbows at your sides, curl without swinging, and control the lowering through a full stretch — constant tension throughout.",
  },
  {
    id: "ez-bar-curl",
    name: "EZ-Bar Curl",
    primaryMuscle: "biceps",
    tier: "A",
    equipment: "barbell",
    repRange: { min: 8, max: 12 },
    targetRIR: 1,
    note: "Keep the elbows still and tucked, squeeze at the top, and resist the negative — no torso rocking.",
  },
  {
    id: "hammer-curl",
    name: "Hammer Curl",
    primaryMuscle: "biceps",
    tier: "A",
    equipment: "dumbbell",
    repRange: { min: 8, max: 12 },
    targetRIR: 1,
    note: "Thor plan: builds arm thickness via the brachialis and forearms. Neutral (palms-facing) grip, elbows fixed at your sides, no swing.",
    tags: ["thor"],
  },
  {
    id: "preacher-curl",
    name: "Preacher Curl",
    primaryMuscle: "biceps",
    tier: "A",
    equipment: "machine",
    repRange: { min: 10, max: 15 },
    targetRIR: 1,
    note: "Thor plan: stretched-position curl with no swinging. Keep the upper arms flat on the pad and control the bottom stretch — don't bounce out of it.",
    tags: ["thor"],
  },

  // ---- QUADS ----
  {
    id: "hack-squat",
    name: "Hack Squat",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes"],
    tier: "S",
    equipment: "machine",
    repRange: { min: 8, max: 12 },
    targetRIR: 1,
    note: "Feet lower/closer for quad bias; descend deep with control and drive through the whole foot on a stable path.",
  },
  {
    id: "leg-press",
    name: "Leg Press",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes"],
    tier: "S",
    equipment: "machine",
    repRange: { min: 10, max: 15 },
    targetRIR: 1,
    note: "Feet mid-platform; lower until the knees reach ~90° (or deeper for range) without the lower back rounding off the pad.",
  },
  {
    id: "barbell-squat",
    name: "Barbell Back Squat",
    primaryMuscle: "quads",
    secondaryMuscles: ["glutes", "hamstrings"],
    tier: "A",
    equipment: "barbell",
    repRange: { min: 6, max: 10 },
    targetRIR: 2,
    note: "Brace the core hard, sit hips and knees down together to at least parallel, with the knees tracking over the toes.",
  },
  {
    id: "leg-extension",
    name: "Leg Extension",
    primaryMuscle: "quads",
    tier: "A",
    equipment: "machine",
    repRange: { min: 12, max: 20 },
    targetRIR: 0,
    note: "Align the knee with the machine's pivot, extend to a hard contraction at the top, and lower slowly.",
  },

  // ---- HAMSTRINGS ----
  {
    id: "seated-leg-curl",
    name: "Seated Leg Curl",
    primaryMuscle: "hamstrings",
    tier: "S",
    equipment: "machine",
    repRange: { min: 10, max: 15 },
    targetRIR: 1,
    note: "Trains the hamstrings in a stretched position (top tier). Curl fully under the seat and control the return.",
  },
  {
    id: "romanian-deadlift",
    name: "Romanian Deadlift",
    primaryMuscle: "hamstrings",
    secondaryMuscles: ["glutes", "back"],
    tier: "S",
    equipment: "barbell",
    repRange: { min: 8, max: 12 },
    targetRIR: 2,
    note: "Push the hips back with soft knees, keep the bar close and the back flat, and stop when you feel the hamstring stretch.",
  },
  {
    id: "lying-leg-curl",
    name: "Lying Leg Curl",
    primaryMuscle: "hamstrings",
    tier: "A",
    equipment: "machine",
    repRange: { min: 10, max: 15 },
    targetRIR: 1,
    note: "Keep the hips pressed into the pad, curl all the way up, and lower under control through the full stretch.",
  },

  // ---- GLUTES ----
  {
    id: "hip-thrust",
    name: "Barbell Hip Thrust",
    primaryMuscle: "glutes",
    secondaryMuscles: ["hamstrings"],
    tier: "S",
    equipment: "barbell",
    repRange: { min: 8, max: 12 },
    targetRIR: 1,
    note: "Upper back on the bench, chin tucked; drive the hips to full lockout and squeeze the glutes hard at the top.",
  },
  {
    id: "cable-kickback",
    name: "Cable Glute Kickback",
    primaryMuscle: "glutes",
    tier: "A",
    equipment: "cable",
    repRange: { min: 12, max: 20 },
    targetRIR: 0,
    note: "Hinge slightly forward and extend the hip by squeezing the glute; don't arch the lower back to finish the rep.",
  },

  // ---- CALVES ----
  {
    id: "standing-calf-raise",
    name: "Standing Calf Raise",
    primaryMuscle: "calves",
    tier: "S",
    equipment: "machine",
    repRange: { min: 8, max: 12 },
    targetRIR: 0,
    note: "Knee straight = gastrocnemius. Pause 1–2s in a deep loaded stretch at the bottom and drive to a full contraction up top — the stretched position drives most of the growth. Isolation, so take it to ~0 RIR.",
  },
  {
    id: "seated-calf-raise",
    name: "Seated Calf Raise",
    primaryMuscle: "calves",
    tier: "S",
    equipment: "machine",
    repRange: { min: 12, max: 20 },
    targetRIR: 0,
    note: "Bent knee targets the soleus — a huge, slow-twitch part of the calf that the standing raise misses, so train both. Higher reps, deep stretch, taken near failure.",
  },
];

// Quick lookup by id.
export const EXERCISE_MAP: Record<string, Exercise> = Object.fromEntries(
  EXERCISES.map((e) => [e.id, e]),
);

export function getExercise(id: string): Exercise | undefined {
  return EXERCISE_MAP[id];
}

const TIER_RANK = { S: 0, A: 1, B: 2 } as const;

// All exercises that primarily train a muscle, ranked best-first (S→A→B, then
// alphabetical). Used to suggest swaps.
export function alternativesForMuscle(muscle: Exercise["primaryMuscle"]): Exercise[] {
  return EXERCISES.filter((e) => e.primaryMuscle === muscle).sort(
    (a, b) => TIER_RANK[a.tier] - TIER_RANK[b.tier] || a.name.localeCompare(b.name),
  );
}
